# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParkNow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParkNow
pod 'RealmSwift'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'BraintreeDropIn'

  target 'ParkNowTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'ParkNowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
